BAD_WORDS = [
    'SA-MP',
    'CodsMP',
    'Connecting',
    'Connected',
    'SERVER:',
    'MOTD:',
    'HUD:',
    'WEATHER:',
    'Saving screenshot',
    '(( ',
    '[ID:',
    'ERROR:',
    'ENGINEINFO:',
    'VEHICLE:',
    'Session lasted',
    '-> Head movements disabled',
    '<======',
    'ENGINE:',
    'PAYCHECK:',
    'PERHATIAN:',
    'KEGUNAAN:',
    'AdmCmd:',
    'Reason:',
    'CMDINFO:',
    '[id:',
    'SHOP:',
    'USAGE:',
    'CHARITY:',
    'BUS:',
    'REQUEST:',
    'WARNING:',
    'Ad:',
    'Contact Info:',
    '[LIVE]',
    'REPORT:',
    'Audio stream:',
    'INSPECT:',
    'TREATMENT:',
    'NOTE:',
    'INFO:',
    'QUIZ:',
    'Admin ',
    '[OOC]',
    'EVENT:',
    'Reloaded custom models.',
    'TRUNK:',
    'RADIO:',
    '=>',
    'MECHANIC:',
    '[NEWS] ',
    'RESPOND:',
    'TELEPORT:',
    'DRUG:',
    'TRAINING:',
    'FLAT:',
    'DRAG:',
    'STUCK:',
    'FRISK:',
    'MAP:',
    'BANK:',
    'RED:'
]
